# Generated by Django 4.2.4 on 2024-10-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'clients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetricsBandwidth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bw_requested', models.FloatField()),
                ('frames', models.IntegerField()),
                ('bytes', models.IntegerField()),
                ('bandwidth', models.FloatField()),
                ('timestamp', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'metrics_bandwidth',
                'managed': False,
            },
        ),
    ]
